CREATE TABLE ALGATRANSITO.VEICULO
(
    ID              BIGINT      NOT NULL AUTO_INCREMENT,
    PROPRIETARIO_ID BIGINT      NOT NULL,
    MARCA           VARCHAR(20) NOT NULL,
    MODELO          VARCHAR(20) NOT NULL,
    PLACA           VARCHAR(7)  NOT NULL,
    STATUS          VARCHAR(20) NOT NULL,
    DATA_CADASTRO   DATETIME    NOT NULL,
    DATA_APREENSAO  DATETIME,
    PRIMARY KEY (ID)
);

ALTER TABLE ALGATRANSITO.VEICULO
    ADD CONSTRAINT FK_VEICULO_PROPRIETARIO
        FOREIGN KEY (PROPRIETARIO_ID) REFERENCES ALGATRANSITO.PROPRIETARIO (ID);

ALTER TABLE ALGATRANSITO.VEICULO
    ADD CONSTRAINT UK_VEICULO UNIQUE (PLACA);